_wandb:
    value:
        cli_version: 0.25.1
        e:
            hg578dtp1tut1yahxgs9764bnlq0xpcm:
                codePath: para.py
                codePathLocal: para.py
                cpu_count: 4
                cpu_count_logical: 4
                disk:
                    /:
                        total: "243885932544"
                        used: "89566679040"
                email: willis.jack.james@gmail.com
                executable: /home/jjw/mgab/venv/bin/python
                git:
                    commit: 5ceb6d179d0e4036f8ca99a70b476468788c6738
                    remote: https://github.com/jackjameswillis/mgab.git
                host: jjwhp
                memory:
                    total: "8195133440"
                os: Linux-6.17.0-19-generic-x86_64-with-glibc2.39
                program: /home/jjw/mgab/para.py
                python: CPython 3.12.3
                root: /home/jjw/mgab
                startedAt: "2026-03-25T21:46:20.258049Z"
                writerId: hg578dtp1tut1yahxgs9764bnlq0xpcm
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "4": 3.12.3
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
