_wandb:
    value:
        cli_version: 0.25.1
        e:
            84wg8pg1q761z1a2cajoopuwy06htaoo:
                codePath: para.py
                codePathLocal: para.py
                cpu_count: 4
                cpu_count_logical: 4
                disk:
                    /:
                        total: "243885932544"
                        used: "110469091328"
                email: willis.jack.james@gmail.com
                executable: /home/jjw/mgab/venv/bin/python
                git:
                    commit: b38b4cf65eaeb874c2edd0f9f75ee81db482f5ce
                    remote: https://github.com/jackjameswillis/mgab.git
                host: jjwhp
                memory:
                    total: "8195129344"
                os: Linux-6.17.0-19-generic-x86_64-with-glibc2.39
                program: /home/jjw/mgab/para.py
                python: CPython 3.12.3
                root: /home/jjw/mgab
                startedAt: "2026-03-27T13:17:01.046917Z"
                writerId: 84wg8pg1q761z1a2cajoopuwy06htaoo
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "4": 3.12.3
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
